name: Randomtest
favicon: null
layout_spectrum: 0.8151708324439824
typography_spectrum: 0.5401461429428309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.05437558190897107
  lightness: 0.3868063234258443
  saturation: 0.9295996795408428
  rhythmicContrast: 0.721343609970063
purpose: []
